export const questions = [
  {
    id: 51,
    question: 'What is the capital of Japan?',
    choices: ['Seoul', 'Tokyo', 'Bangkok', 'Taipei'],
    answerIndex: 1,
  },
  {
    id: 52,
    question: 'Which ocean is the largest?',
    choices: ['Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean', 'Pacific Ocean'],
    answerIndex: 3,
  },
  {
    id: 53,
    question: 'What is 9 × 7?',
    choices: ['54', '63', '72', '81'],
    answerIndex: 1,
  },
  {
    id: 54,
    question: 'What does CSS stand for?',
    choices: ['Computer Style Sheets', 'Cascading Style Sheets', 'Creative Style System', 'Colorful Style Syntax'],
    answerIndex: 1,
  },
  {
    id: 55,
    question: 'What is the chemical symbol for gold?',
    choices: ['Ag', 'Au', 'Gd', 'Go'],
    answerIndex: 1,
  },
  {
    id: 56,
    question: 'How many sides does a hexagon have?',
    choices: ['4', '5', '6', '7'],
    answerIndex: 2,
  },
  {
    id: 57,
    question: 'What is the fastest land animal?',
    choices: ['Horse', 'Lion', 'Cheetah', 'Gazelle'],
    answerIndex: 2,
  },
  {
    id: 58,
    question: 'Which organ pumps blood through the body?',
    choices: ['Lungs', 'Heart', 'Brain', 'Liver'],
    answerIndex: 1,
  },
  {
    id: 59,
    question: 'What is the approximate value of pi?',
    choices: ['2.14', '3.14', '4.14', '5.14'],
    answerIndex: 1,
  },
  {
    id: 60,
    question: 'Who wrote Hamlet?',
    choices: ['Charles Dickens', 'William Shakespeare', 'Jane Austen', 'Mark Twain'],
    answerIndex: 1,
  },
  {
    id: 61,
    question: 'Which planet is the largest?',
    choices: ['Mars', 'Venus', 'Jupiter', 'Saturn'],
    answerIndex: 2,
  },
  {
    id: 62,
    question: 'What is the main gas found in Earth’s atmosphere?',
    choices: ['Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Hydrogen'],
    answerIndex: 2,
  },
  {
    id: 63,
    question: 'Who wrote 1984?',
    choices: ['George Orwell', 'Aldous Huxley', 'Ray Bradbury', 'J. R. R. Tolkien'],
    answerIndex: 0,
  },
  {
    id: 64,
    question: 'What color is the sky on a clear day?',
    choices: ['Green', 'Blue', 'Red', 'Yellow'],
    answerIndex: 1,
  },
  {
    id: 65,
    question: 'How many months are there in a year?',
    choices: ['10', '11', '12', '13'],
    answerIndex: 2,
  },
  {
    id: 66,
    question: 'What is the national animal of India?',
    choices: ['Elephant', 'Tiger', 'Lion', 'Peacock'],
    answerIndex: 1,
  },
  {
    id: 67,
    question: 'At what temperature does water freeze in Celsius?',
    choices: ['0°C', '10°C', '100°C', '-10°C'],
    answerIndex: 0,
  },
  {
    id: 68,
    question: 'Which is the smallest continent?',
    choices: ['Asia', 'Africa', 'Australia', 'Europe'],
    answerIndex: 2,
  },
  {
    id: 69,
    question: 'What is the currency of Brazil?',
    choices: ['Peso', 'Dollar', 'Real', 'Yen'],
    answerIndex: 2,
  },
  {
    id: 70,
    question: 'How many bones are there in an adult human body?',
    choices: ['180', '206', '220', '260'],
    answerIndex: 1,
  },
  {
    id: 71,
    question: 'What does CPU stand for?',
    choices: ['Central Processing Unit', 'Computer Program Unit', 'Central Power Unit', 'Control Processing Unit'],
    answerIndex: 0,
  },
  {
    id: 72,
    question: 'Which gas do plants absorb from the air?',
    choices: ['Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Hydrogen'],
    answerIndex: 2,
  },
  {
    id: 73,
    question: 'Which river is the longest in the world?',
    choices: ['Amazon', 'Nile', 'Yangtze', 'Mississippi'],
    answerIndex: 1,
  },
  {
    id: 74,
    question: 'Who painted the Mona Lisa?',
    choices: ['Vincent van Gogh', 'Pablo Picasso', 'Leonardo da Vinci', 'Claude Monet'],
    answerIndex: 2,
  },
  {
    id: 75,
    question: 'Which is the largest desert in the world?',
    choices: ['Gobi', 'Arabian', 'Antarctic', 'Sahara'],
    answerIndex: 2,
  },
  {
    id: 76,
    question: 'Who discovered gravity?',
    choices: ['Albert Einstein', 'Isaac Newton', 'Galileo Galilei', 'Nikola Tesla'],
    answerIndex: 1,
  },
  {
    id: 77,
    question: 'How many days are there in a leap year?',
    choices: ['364', '365', '366', '367'],
    answerIndex: 2,
  },
  {
    id: 78,
    question: 'What is the capital of Australia?',
    choices: ['Sydney', 'Melbourne', 'Canberra', 'Perth'],
    answerIndex: 2,
  },
  {
    id: 79,
    question: 'What is the chemical symbol for sodium?',
    choices: ['S', 'So', 'Na', 'Sd'],
    answerIndex: 2,
  },
  {
    id: 80,
    question: 'Which of these is not a mammal?',
    choices: ['Whale', 'Dolphin', 'Shark', 'Bat'],
    answerIndex: 2,
  },
  {
    id: 81,
    question: 'What does HTML stand for?',
    choices: ['Hyper Text Markup Language', 'High Transfer Markup Language', 'Home Tool Markup Language', 'Hyperlink Text Machine Language'],
    answerIndex: 0,
  },
  {
    id: 82,
    question: 'Which planet is often called the Morning Star?',
    choices: ['Mars', 'Mercury', 'Venus', 'Saturn'],
    answerIndex: 2,
  },
  {
    id: 83,
    question: 'Who was the first person to walk on the Moon?',
    choices: ['Buzz Aldrin', 'Yuri Gagarin', 'Neil Armstrong', 'John Glenn'],
    answerIndex: 2,
  },
  {
    id: 84,
    question: 'Which country has a maple leaf on its flag?',
    choices: ['USA', 'Canada', 'Mexico', 'Brazil'],
    answerIndex: 1,
  },
  {
    id: 85,
    question: 'What is the largest mammal in the world?',
    choices: ['Elephant', 'Blue Whale', 'Giraffe', 'Hippopotamus'],
    answerIndex: 1,
  },
  {
    id: 86,
    question: 'Which gas is commonly used in balloons?',
    choices: ['Oxygen', 'Helium', 'Nitrogen', 'Carbon Dioxide'],
    answerIndex: 1,
  },
  {
    id: 87,
    question: 'What is 12²?',
    choices: ['122', '144', '132', '124'],
    answerIndex: 1,
  },
  {
    id: 88,
    question: 'What is the capital of Egypt?',
    choices: ['Cairo', 'Alexandria', 'Giza', 'Luxor'],
    answerIndex: 0,
  },
  {
    id: 89,
    question: 'Which bird can fly backward?',
    choices: ['Eagle', 'Hummingbird', 'Sparrow', 'Penguin'],
    answerIndex: 1,
  },
  {
    id: 90,
    question: 'Which is a renewable source of energy?',
    choices: ['Coal', 'Oil', 'Wind', 'Natural Gas'],
    answerIndex: 2,
  },
  {
    id: 91,
    question: 'How many weeks are there in a year?',
    choices: ['48', '50', '52', '54'],
    answerIndex: 2,
  },
  {
    id: 92,
    question: 'What instrument is used to measure temperature?',
    choices: ['Barometer', 'Thermometer', 'Altimeter', 'Hygrometer'],
    answerIndex: 1,
  },
  {
    id: 93,
    question: 'Who wrote Romeo and Juliet?',
    choices: ['Charles Dickens', 'William Shakespeare', 'Jane Austen', 'George Orwell'],
    answerIndex: 1,
  },
  {
    id: 94,
    question: 'Which animal has black and white stripes?',
    choices: ['Tiger', 'Zebra', 'Giraffe', 'Leopard'],
    answerIndex: 1,
  },
  {
    id: 95,
    question: 'What is the capital of South Africa?',
    choices: ['Cape Town', 'Johannesburg', 'Pretoria', 'Durban'],
    answerIndex: 2,
  },
  {
    id: 96,
    question: 'What is the square root of 64?',
    choices: ['6', '7', '8', '9'],
    answerIndex: 2,
  },
  {
    id: 97,
    question: 'Which layer of the Earth do we live on?',
    choices: ['Core', 'Mantle', 'Crust', 'Atmosphere'],
    answerIndex: 2,
  },
  {
    id: 98,
    question: 'Who is known as the father of computers?',
    choices: ['Alan Turing', 'Charles Babbage', 'Steve Jobs', 'Bill Gates'],
    answerIndex: 1,
  },
  {
    id: 99,
    question: 'What color do you get by mixing red and blue?',
    choices: ['Green', 'Orange', 'Purple', 'Brown'],
    answerIndex: 2,
  },
  {
    id: 100,
    question: 'What is the capital of Italy?',
    choices: ['Milan', 'Rome', 'Florence', 'Venice'],
    answerIndex: 1,
  },
  {
    id: 101,
    question: 'What is 15% of 200?',
    choices: ['15', '20', '30', '40'],
    answerIndex: 2,
  },
  {
    id: 102,
    question: 'Which country is called the Land of the Rising Sun?',
    choices: ['China', 'Japan', 'South Korea', 'Thailand'],
    answerIndex: 1,
  },
  {
    id: 103,
    question: 'What is the smallest prime number?',
    choices: ['0', '1', '2', '3'],
    answerIndex: 2,
  },
  {
    id: 104,
    question: 'Who invented the telephone?',
    choices: ['Thomas Edison', 'Alexander Graham Bell', 'Nikola Tesla', 'Marie Curie'],
    answerIndex: 1,
  },
  {
    id: 105,
    question: 'What is the largest bone in the human body?',
    choices: ['Skull', 'Femur', 'Tibia', 'Humerus'],
    answerIndex: 1,
  },
  {
    id: 106,
    question: 'What is the name of our galaxy?',
    choices: ['Andromeda', 'Milky Way', 'Orion', 'Triangulum'],
    answerIndex: 1,
  },
  {
    id: 107,
    question: 'What is the capital of Turkey?',
    choices: ['Istanbul', 'Ankara', 'Izmir', 'Antalya'],
    answerIndex: 1,
  },
  {
    id: 108,
    question: 'Which planet is closest to the Sun?',
    choices: ['Venus', 'Mercury', 'Mars', 'Earth'],
    answerIndex: 1,
  },
  {
    id: 109,
    question: 'What is the formula for the area of a rectangle?',
    choices: ['length × width', 'length + width', '2 × length', 'width ÷ length'],
    answerIndex: 0,
  },
  {
    id: 110,
    question: 'What does WWW stand for?',
    choices: ['World Wide Web', 'World Wide Work', 'Web World Wide', 'Wide Web World'],
    answerIndex: 0,
  },
  {
    id: 111,
    question: 'What element has the symbol O?',
    choices: ['Gold', 'Oxygen', 'Osmium', 'Argon'],
    answerIndex: 1,
  },
  {
    id: 112,
    question: 'Where is the Eiffel Tower located?',
    choices: ['London', 'Rome', 'Paris', 'Berlin'],
    answerIndex: 2,
  },
  {
    id: 113,
    question: 'What is 3/4 as a percentage?',
    choices: ['25%', '50%', '75%', '100%'],
    answerIndex: 2,
  },
  {
    id: 114,
    question: 'What is the currency of Japan?',
    choices: ['Yuan', 'Won', 'Yen', 'Rupee'],
    answerIndex: 2,
  },
  {
    id: 115,
    question: 'What is 2⁵?',
    choices: ['8', '16', '32', '64'],
    answerIndex: 2,
  },
  {
    id: 116,
    question: 'Which sea lies between Europe and Africa?',
    choices: ['Black Sea', 'Mediterranean Sea', 'Red Sea', 'North Sea'],
    answerIndex: 1,
  },
  {
    id: 117,
    question: 'Who wrote The Odyssey?',
    choices: ['Homer', 'Virgil', 'Socrates', 'Plato'],
    answerIndex: 0,
  },
  {
    id: 118,
    question: 'What does DNA stand for?',
    choices: ['Deoxyribonucleic Acid', 'Dynamic Nucleic Acid', 'Digital Nuclear Array', 'Double Nucleic Atom'],
    answerIndex: 0,
  },
  {
    id: 119,
    question: 'Which is the largest continent?',
    choices: ['Africa', 'Europe', 'Asia', 'South America'],
    answerIndex: 2,
  },
  {
    id: 120,
    question: 'What is the capital of Mexico?',
    choices: ['Mexico City', 'Guadalajara', 'Monterrey', 'Cancun'],
    answerIndex: 0,
  },
  {
    id: 121,
    question: 'Which of these is a noble gas?',
    choices: ['Oxygen', 'Neon', 'Nitrogen', 'Hydrogen'],
    answerIndex: 1,
  },
  {
    id: 122,
    question: 'What is 100 ÷ 4?',
    choices: ['20', '24', '25', '30'],
    answerIndex: 2,
  },
  {
    id: 123,
    question: 'What is the hardest natural substance on Earth?',
    choices: ['Steel', 'Quartz', 'Diamond', 'Granite'],
    answerIndex: 2,
  },
  {
    id: 124,
    question: 'Which animal is known as the king of the jungle?',
    choices: ['Tiger', 'Lion', 'Elephant', 'Wolf'],
    answerIndex: 1,
  },
  {
    id: 125,
    question: 'What is the capital of Russia?',
    choices: ['Saint Petersburg', 'Moscow', 'Kazan', 'Novosibirsk'],
    answerIndex: 1,
  },
  {
    id: 126,
    question: 'What is the freezing point of water in Fahrenheit?',
    choices: ['0°F', '32°F', '212°F', '100°F'],
    answerIndex: 1,
  },
  {
    id: 127,
    question: 'Who discovered penicillin?',
    choices: ['Louis Pasteur', 'Alexander Fleming', 'Robert Koch', 'Marie Curie'],
    answerIndex: 1,
  },
  {
    id: 128,
    question: 'What is the main ingredient in glass?',
    choices: ['Clay', 'Sand', 'Limestone', 'Salt'],
    answerIndex: 1,
  },
  {
    id: 129,
    question: 'What is the capital of Spain?',
    choices: ['Barcelona', 'Madrid', 'Seville', 'Valencia'],
    answerIndex: 1,
  },
  {
    id: 130,
    question: 'Which planet is known for its rings?',
    choices: ['Mars', 'Jupiter', 'Saturn', 'Neptune'],
    answerIndex: 2,
  },
  {
    id: 131,
    question: 'What is 7²?',
    choices: ['42', '49', '56', '63'],
    answerIndex: 1,
  },
  {
    id: 132,
    question: 'Which country is the largest by land area?',
    choices: ['Canada', 'China', 'Russia', 'USA'],
    answerIndex: 2,
  },
  {
    id: 133,
    question: 'What is the chemical symbol for potassium?',
    choices: ['P', 'Po', 'K', 'Pt'],
    answerIndex: 2,
  },
  {
    id: 134,
    question: 'What is the capital of Canada?',
    choices: ['Toronto', 'Montreal', 'Ottawa', 'Vancouver'],
    answerIndex: 2,
  },
  {
    id: 135,
    question: 'Who painted The Starry Night?',
    choices: ['Claude Monet', 'Vincent van Gogh', 'Edgar Degas', 'Salvador Dalí'],
    answerIndex: 1,
  },
  {
    id: 136,
    question: 'Which part of a plant absorbs water from the soil?',
    choices: ['Leaves', 'Flowers', 'Roots', 'Stem'],
    answerIndex: 2,
  },
  {
    id: 137,
    question: 'What is 20% of 80?',
    choices: ['8', '12', '16', '20'],
    answerIndex: 2,
  },
  {
    id: 138,
    question: 'What does GPS stand for?',
    choices: ['Global Positioning System', 'General Power System', 'Global Positioning Satellite', 'Geographic Positioning Service'],
    answerIndex: 0,
  },
  {
    id: 139,
    question: 'What is the capital of Norway?',
    choices: ['Bergen', 'Oslo', 'Trondheim', 'Stavanger'],
    answerIndex: 1,
  },
  {
    id: 140,
    question: 'Which animal lays eggs and has fur?',
    choices: ['Dolphin', 'Platypus', 'Koala', 'Rabbit'],
    answerIndex: 1,
  },
  {
    id: 141,
    question: 'What is 5!?',
    choices: ['100', '110', '120', '130'],
    answerIndex: 2,
  },
  {
    id: 142,
    question: 'What is the largest internal organ in the human body?',
    choices: ['Heart', 'Liver', 'Lungs', 'Kidney'],
    answerIndex: 1,
  },
  {
    id: 143,
    question: 'Which country is shaped like a boot?',
    choices: ['Spain', 'Italy', 'Greece', 'Portugal'],
    answerIndex: 1,
  },
  {
    id: 144,
    question: 'Who wrote Pride and Prejudice?',
    choices: ['Emily Brontë', 'Jane Austen', 'Charlotte Brontë', 'Virginia Woolf'],
    answerIndex: 1,
  },
  {
    id: 145,
    question: 'What is the chemical symbol for carbon?',
    choices: ['C', 'Ca', 'Co', 'Cr'],
    answerIndex: 0,
  },
  {
    id: 146,
    question: 'What is the capital of Argentina?',
    choices: ['Buenos Aires', 'Cordoba', 'Rosario', 'Mendoza'],
    answerIndex: 0,
  },
  {
    id: 147,
    question: 'Which ocean is the coldest?',
    choices: ['Atlantic', 'Indian', 'Arctic', 'Pacific'],
    answerIndex: 2,
  },
  {
    id: 148,
    question: 'What is the sum of 12 and 18?',
    choices: ['24', '28', '30', '32'],
    answerIndex: 2,
  },
  {
    id: 149,
    question: 'What is the currency of the United Kingdom?',
    choices: ['Euro', 'Dollar', 'Pound Sterling', 'Yen'],
    answerIndex: 2,
  },
  {
    id: 150,
    question: 'Which instrument is used to see tiny things?',
    choices: ['Microscope', 'Telescope', 'Periscope', 'Stethoscope'],
    answerIndex: 0,
  },
  {
    id: 151,
    question: 'What is the capital of South Korea?',
    choices: ['Busan', 'Seoul', 'Daegu', 'Incheon'],
    answerIndex: 1,
  },
  {
    id: 152,
    question: 'Which gas do humans breathe in?',
    choices: ['Carbon Dioxide', 'Hydrogen', 'Oxygen', 'Nitrogen'],
    answerIndex: 2,
  },
  {
    id: 153,
    question: 'What is 1/2 of 50?',
    choices: ['20', '25', '30', '35'],
    answerIndex: 1,
  },
  {
    id: 154,
    question: 'Which planet is known as the evening star?',
    choices: ['Mars', 'Mercury', 'Venus', 'Saturn'],
    answerIndex: 2,
  },
  {
    id: 155,
    question: 'What is the capital of Thailand?',
    choices: ['Chiang Mai', 'Bangkok', 'Phuket', 'Pattaya'],
    answerIndex: 1,
  },
  {
    id: 156,
    question: 'What is the first element in the periodic table?',
    choices: ['Helium', 'Hydrogen', 'Lithium', 'Oxygen'],
    answerIndex: 1,
  },
  {
    id: 157,
    question: 'Which country is known as the Pearl of Africa?',
    choices: ['Kenya', 'Uganda', 'Tanzania', 'Rwanda'],
    answerIndex: 1,
  },
  {
    id: 158,
    question: 'What is 18 ÷ 3?',
    choices: ['4', '5', '6', '7'],
    answerIndex: 2,
  },
  {
    id: 159,
    question: 'Who is the author of The Great Gatsby?',
    choices: ['Ernest Hemingway', 'F. Scott Fitzgerald', 'J. D. Salinger', 'John Steinbeck'],
    answerIndex: 1,
  },
  {
    id: 160,
    question: 'What is the capital of the Philippines?',
    choices: ['Cebu City', 'Manila', 'Davao City', 'Quezon City'],
    answerIndex: 1,
  },
  {
    id: 161,
    question: 'Which organ filters blood in the body?',
    choices: ['Liver', 'Kidney', 'Lung', 'Pancreas'],
    answerIndex: 1,
  },
  {
    id: 162,
    question: 'What is 9²?',
    choices: ['72', '81', '90', '99'],
    answerIndex: 1,
  },
  {
    id: 163,
    question: 'What is the currency of India?',
    choices: ['Yen', 'Rupee', 'Baht', 'Peso'],
    answerIndex: 1,
  },
  {
    id: 164,
    question: 'Which animal is the fastest swimmer?',
    choices: ['Sailfish', 'Turtle', 'Octopus', 'Whale'],
    answerIndex: 0,
  },
  {
    id: 165,
    question: 'What is the capital of Vietnam?',
    choices: ['Ho Chi Minh City', 'Hanoi', 'Da Nang', 'Hai Phong'],
    answerIndex: 1,
  },
  {
    id: 166,
    question: 'What is the square root of 81?',
    choices: ['7', '8', '9', '10'],
    answerIndex: 2,
  },
  {
    id: 167,
    question: 'Which planet is the smallest?',
    choices: ['Mars', 'Mercury', 'Venus', 'Earth'],
    answerIndex: 1,
  },
  {
    id: 168,
    question: 'What is 8 × 9?',
    choices: ['64', '70', '72', '80'],
    answerIndex: 2,
  },
  {
    id: 169,
    question: 'Who wrote the Harry Potter books?',
    choices: ['Stephen King', 'J. K. Rowling', 'Suzanne Collins', 'Rick Riordan'],
    answerIndex: 1,
  },
  {
    id: 170,
    question: 'What is the capital of Germany?',
    choices: ['Munich', 'Frankfurt', 'Berlin', 'Hamburg'],
    answerIndex: 2,
  },
];

